const { GoogleGenAI } = require('@google/genai');
const z = require('zod');

const genai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY
});

const interviewReportSchema = z.object({
  matchScore: z.number().describe("A score indicating how well the candidate's resume and self-description match the job description"),
  technicalQuestions: z.array(z.object({
    question: z.string().describe("The technical question can be asked during the interview"),
    intention: z.string().describe("The intention behind asking this question"),
    answers: z.string().describe("The ideal answer for this question and also the points to be noted while answering this question")
  })).describe("A list of technical questions that can be asked during the interview"),
  behavioralQuestions: z.array(z.object({
    question: z.string().describe("The behavioral question can be asked during the interview"),
    intention: z.string().describe("The intention behind asking this question"),
    answers: z.string().describe("The ideal answer for this question and also the points to be noted while answering this question")
  })).describe("A list of behavioral questions that can be asked during the interview"),
  skillGaps: z.array(z.object({
    skill: z.string().describe("The skill in which the candidate is lacking"),
    severity: z.enum(['Low', 'Medium', 'High']).describe("The severity of the skill gap")
  })).describe("A list of skill gaps that the candidate has along with the severity"),
  preparationPlan: z.array(z.object({
    day: z.number().describe("The day number for which the preparation plan is provided"),
    focusArea: z.string().describe("The focus area for the preparation on that day"),
    task: z.array(z.string()).describe("The list of tasks to be done on that day for preparation")
  })).describe("A day-wise preparation plan for the candidate to prepare for the interview"),
  title: z.string().describe("The title of the job for which the interview report is generated")
}).describe("The schema for the interview report generated by GenAI based on the job description, resume and self-description provided by the candidate");

const generateInterviewReport = async ({ resume, selfDescription, jobDescription }) => {
  try {
    const prompt = `
You are an expert interviewer.

Return ONLY valid JSON. No explanation.

STRICT RULES:
- Do NOT return undefined
- Do NOT skip any field
- Do NOT use null
- All fields are REQUIRED

JSON FORMAT:
{
  "title": "string",
  "matchScore": 85,
  "technicalQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answers": "string"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "string",
      "intention": "string",
      "answers": "string"
    }
  ],
  "skillGaps": [
    {
      "skill": "string",
      "severity": "Low"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focusArea": "string",
      "task": ["string", "string"]
    }
  ]
}

Generate:
- 1 title
- 5 technicalQuestions
- 5 behavioralQuestions
- 3 skillGaps
- 5 preparationPlan

Job Description:
${jobDescription}

Resume:
${resume}

Self Description:
${selfDescription}
`;

    const response = await genai.models.generateContent({
      model: process.env.GEMINI_MODEL || 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json'
      }
    });

    const text =
      response.text ||
      response.candidates?.[0]?.content?.parts?.[0]?.text;

    if (!text) {
      throw new Error('Invalid AI response');
    }

    const parsed = JSON.parse(text);
    const validated = interviewReportSchema.safeParse(parsed);

    if (!validated.success) {
      console.error('Zod Error:', validated.error);
      throw new Error('AI response schema mismatch');
    }

    return validated.data;
  } catch (error) {
    console.error('GenAI error:', error);
    throw new Error('Failed to generate interview report');
  }
};

module.exports = generateInterviewReport;
